name: Test deploy-to-k8s

on:
  push:
    branches:
      - feature/ASE-55-init-action
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run the local action
        uses: ./
